CREATE OR REPLACE PACKAGE LTSYS.GEN_BILET_PKG AS 

PROCEDURE GEN_BILET_5_5_8;

PROCEDURE GEN_BILET_4_4_9;

PROCEDURE GEN_BILET_4_4_8;

PROCEDURE GEN_BILET_4_4_10;

PROCEDURE GEN_BILET_3_3_12;

END GEN_BILET_PKG;
